name: StaticWeb

on:
  repository_dispatch:
    types: [deployment]
  workflow_dispatch:
    
jobs:
  build:
    name: Build Jekyll Website
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Add env to Github
        run: |
          echo $GEM_HOME/bin >> $HOME/.bashrc
          source $HOME/.bashrc
          echo $PATH
        env:
          GEM_HOME: "$HOME/gems"
        shell: bash
        
      - name: Check Ruby is installed or not
        run: |
          ruby -v
          
      - name: install bundler
        run: |
          gem install jekyll bundler
